# Generated by Django 4.2.11 on 2026-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_cantidad_entregada_stockegresoitems_cantidad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='codigo_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Item'),
        ),
    ]
