# Generated by Django 4.2.11 on 2026-05-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_items_codigo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creador', models.CharField(blank=True, max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventario_proveedores',
            },
        ),
    ]
