# Generated by Django 4.2.11 on 2026-05-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_proveedorinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoCasaMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_buenos', models.IntegerField(default=0)),
                ('cantidad_malos', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/ingresos_cm/')),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('creador', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.proveedorinventario')),
            ],
            options={
                'db_table': 'inventario_ingreso_casa_matriz',
            },
        ),
    ]
