# Generated by Django 4.2.11 on 2026-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_ingresocasamatriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresocasamatriz',
            name='valor_neto',
            field=models.IntegerField(default=0, verbose_name='Valor Neto'),
        ),
    ]
