# Generated by Django 4.2.11 on 2026-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_ingresocasamatriz_valor_neto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodegaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creador', models.CharField(blank=True, max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventario_bodegas',
            },
        ),
    ]
