# Generated by Django 4.2.11 on 2026-06-04 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_bodegainventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoBodegaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_tipo', models.CharField(max_length=20)),
                ('destino_tipo', models.CharField(max_length=20)),
                ('cantidad_buenos', models.IntegerField(default=0)),
                ('cantidad_malos', models.IntegerField(default=0)),
                ('creador', models.CharField(blank=True, max_length=100, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('destino_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='inventory.bodegainventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('origen_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='inventory.bodegainventario')),
            ],
            options={
                'db_table': 'inventario_traspaso_bodega',
            },
        ),
        migrations.CreateModel(
            name='StockUbicacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(choices=[('CASA_MATRIZ', 'Casa Matriz'), ('BODEGA', 'Bodega')], max_length=20)),
                ('cantidad_buenos', models.IntegerField(default=0)),
                ('cantidad_malos', models.IntegerField(default=0)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.bodegainventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
            options={
                'db_table': 'inventario_stock_ubicacion',
                'unique_together': {('item', 'tipo_ubicacion', 'bodega')},
            },
        ),
    ]
