# Generated by Django 4.2.11 on 2026-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_traspasobodegainventario_stockubicacioninventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockubicacioninventario',
            name='stock_alarma',
            field=models.IntegerField(default=0),
        ),
    ]
