# Generated by Django 4.2.11 on 2026-04-29 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador Único')),
                ('external_emails', models.JSONField(blank=True, default=list, verbose_name='Emails Externos')),
                ('users', models.ManyToManyField(blank=True, related_name='notification_groups', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del Sistema')),
            ],
            options={
                'verbose_name': 'Grupo de Notificación',
                'verbose_name_plural': 'Grupos de Notificaciones',
            },
        ),
    ]
