# Generated by Django 4.2.11 on 2026-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgroup',
            name='category',
            field=models.CharField(choices=[('VEHICULAR', 'Gestión Vehicular'), ('SONDAJE', 'Sondaje (Drilling)'), ('PREVENCION', 'Prevención de Riesgos'), ('SISTEMA', 'Mantenimiento del Sistema')], default='VEHICULAR', max_length=20, verbose_name='Categoría'),
        ),
    ]
