# Generated by Django 4.2.11 on 2026-04-21 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_programa_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=200, unique=True, verbose_name='Problema')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Problema de Vehículo',
                'verbose_name_plural': 'Problemas de Vehículos',
                'db_table': 'vehicle_problem',
            },
        ),
    ]
