# Generated by Django 4.2.11 on 2026-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_problemavehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentofaenageneral',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad'),
        ),
    ]
