# Generated by Django 4.2.11 on 2026-04-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_tipodocumentofaenageneral_fecha_caducidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumentofaenageneral',
            old_name='fecha_caducidad',
            new_name='fechacaducidad',
        ),
    ]
