# Generated by Django 4.2.11 on 2026-05-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_rename_fecha_caducidad_tipodocumentofaenageneral_fechacaducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoGrua',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Grua (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoMantencion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Mantención (Opcional)'),
        ),
        migrations.AlterField(
            model_name='ocultaropcionesvehiculo',
            name='fechaCertificadoOperatividad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=10, null=True, verbose_name='Certificado Operatividad (Opcional)'),
        ),
    ]
