# Generated by Django 4.2.11 on 2026-03-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0018_vigilanciaarea_vigilanciacargo_and_more'),
        ('user', '0008_usuarioprofile_seccioninformaciontecnica'),
    ]

    operations = [
        # Nueva tabla para persistir información laboral reutilizable por Vigilancia Médica.
        migrations.CreateModel(
            name='UserInformacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('fechaDesvinculacion', models.DateField(blank=True, null=True, verbose_name='Fecha Desvinculación')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_informacion_laboral_area', to='prevencion.vigilanciaarea')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_informacion_laboral_cargo', to='prevencion.vigilanciacargo')),
                ('ges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_informacion_laboral_ges', to='prevencion.vigilanciages')),
                ('tipo_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_informacion_laboral_tipo_contrato', to='prevencion.vigilanciatipocontrato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_laboral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Información Laboral',
                'verbose_name_plural': 'Información Laboral',
                'db_table': 'user_informacion_laboral',
            },
        ),
    ]
