# Generated by Django 4.2.11 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userinformacionlaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('ADMINISTRADOR', 'Administrador'),
                    ('JEFE MANTENCION', 'Jefe Mantencion'),
                    ('SUPERVISOR', 'Supervisor'),
                    ('CONTROLADOR', 'Controlador'),
                    ('PERFORISTA', 'Perforista'),
                    ('BASE DATOS', 'Base de Datos'),
                    ('CONDUCTOR', 'Conductor'),
                    ('TRABAJADOR', 'Trabajador'),
                    ('SIN ASIGNAR', 'Sin Asignar'),
                ],
                max_length=50,
                verbose_name='Rol',
            ),
        ),
    ]
