# Generated by Django 4.2.11 on 2026-03-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0023_egreso_higienecualitativa_higienecuantitativa_and_more'),
        ('user', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformacionlaboral',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_informacion_laboral_contrato', to='prevencion.vigilanciacontrato'),
        ),
    ]
