# Generated by Django 4.2.11 on 2026-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userinformacionlaboral_contrato'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
