# Generated by Django 4.2.11 on 2026-05-08 01:32

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.AuditableUserManager()),
            ],
        ),
    ]
