# Generated by Django 4.2.11 on 2026-05-05 18:32

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.AuditableUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionInformacionTecnica',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Información Técnica'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionInventario',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Inventario'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionPrevencion',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Prevención de Riesgos'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionSondaje',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Sondaje'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionVehicular',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Vehicular'),
        ),
    ]
