# Generated by Django 4.2.11 on 2026-05-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionInformacionTecnica',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Información Técnica'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionInventario',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Inventario'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionPrevencion',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Prevención de Riesgos'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionSondaje',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Sondaje'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionVehicular',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Vehicular'),
        ),
    ]
