# Generated by Django 4.2.11 on 2026-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioprofile',
            name='seccionInformacionTecnica',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Administración'),
        ),
    ]
