# Generated by Django 4.2.11 on 2026-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_usuarioprofile_seccioninformaciontecnica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioprofile',
            name='seccionInformacionTecnica',
        ),
        migrations.AddField(
            model_name='usuarioprofile',
            name='seccionAdministracion',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, null=True, verbose_name='Rol Sección Administración'),
        ),
    ]
