# Generated by Django 4.2.11 on 2026-05-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_managers'),
        ('user', '0018_remove_usuarioprofile_seccioninformaciontecnica_and_more'),
    ]

    operations = [
    ]
