# Generated by Django 4.2.11 on 2026-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_merge_20260511_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('JEFE MANTENCION', 'Jefe Mantencion'), ('SUPERVISOR', 'Supervisor'), ('CONTROLADOR', 'Controlador'), ('PERFORISTA', 'Perforista'), ('BASE DATOS', 'Base de Datos'), ('CONDUCTOR', 'Conductor'), ('TRABAJADOR', 'Trabajador'), ('PREVENCIONISTA', 'Prevencionista'), ('SIN ASIGNAR', 'Sin Asignar')], default='SIN ASIGNAR', max_length=50, verbose_name='Rol'),
        ),
    ]
