# Generated by Django 4.2.11 on 2026-05-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_role'),
        ('user', '0020_alter_user_role_and_more'),
    ]

    operations = [
    ]
