# Generated by Django 4.2.11 on 2026-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_kitsmaquinariafaena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
