# Generated by Django 5.1.1 on 2026-03-18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drilling', '0022_alter_documentosreportesperforaciones_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantesPerforacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(null=True, verbose_name='Estado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drilling.reportesoperacionales')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usuario', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Participante de Perforación',
                'verbose_name_plural': 'Participantes de Perforación',
                'db_table': 'drilling_reporte_digital_participantes',
            },
        ),
    ]
