# Generated by Django 4.2.11 on 2026-04-17 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0040_remove_ayudatecnicavehiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoFacturaCompra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Factura'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoPadron',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Padrón'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoRevisionTecnicaGases',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Gases'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoSeguroAutomotriz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Seguro Automotriz'),
        ),
        migrations.CreateModel(
            name='HistorialDocumentacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_modificado', models.CharField(max_length=100, verbose_name='Documento Modificado')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('archivo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del Archivo')),
                ('creador', models.CharField(max_length=100, null=True, verbose_name='Usuario')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiculo')),
            ],
            options={
                'verbose_name': 'Historial de Documentación',
                'verbose_name_plural': 'Historiales de Documentación',
                'db_table': 'vehicle_documentation_history',
            },
        ),
    ]
