# Generated by Django 4.2.11 on 2026-04-20 20:25

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0041_vehiculo_fechavencimientofacturacompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacionesvehiculo',
            name='fotografiaTraspasoVenta',
            field=models.ImageField(blank=True, default='documentacion_vehiculo/no-imagen.png', null=True, upload_to=vehicle.models.DocumentacionesVehiculo.generaNombre, verbose_name='Traspaso/Venta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaVencimientoTraspasoVenta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento Traspaso/Venta'),
        ),
    ]
