# Generated by Django 4.2.11 on 2026-04-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_problemavehiculo'),
        ('vehicle', '0042_documentacionesvehiculo_fotografiatraspasoventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.problemavehiculo', verbose_name='Motivo de Desactivación'),
        ),
    ]
