# Generated by Django 4.2.11 on 2026-04-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0043_vehiculo_problema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraccionesvehiculo',
            options={'verbose_name': 'Información Infracción y Multas', 'verbose_name_plural': 'Información Infracciones y Multas'},
        ),
    ]
