# Generated by Django 4.2.11 on 2026-01-19 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0058_recomendacion_fechaupdateestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Checklist Silice Faena Norte', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('tipo', models.CharField(choices=[('condiciones', 'Condiciones Generales'), ('silice', 'Silice'), ('ruido', 'Ruido'), ('hipobaria', 'Hipobaria'), ('psicosocial', 'Psicosocial'), ('tmert', 'TMERT'), ('mmc', 'MMC')], max_length=20, verbose_name='Tipo de Riesgo')),
                ('estructura', models.JSONField(default=list, verbose_name='Estructura Dinámica')),
                ('creador', models.CharField(max_length=50, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_prevencion', to='core.faena', verbose_name='Faena')),
            ],
            options={
                'verbose_name': 'Plantilla de Prevención',
                'verbose_name_plural': 'Plantillas de Prevención',
                'db_table': 'prevencion_plantilla',
            },
        ),
    ]
