# Generated by Django 4.2.11 on 2026-01-19 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_recomendacion_fechaupdateestado'),
        ('prevencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField(verbose_name='Contenido Relleno (Snapshot)')),
                ('evidencia_general', models.FileField(blank=True, null=True, upload_to='prevencion/evidencias/', verbose_name='Archivo General')),
                ('observacion_general', models.TextField(blank=True, null=True)),
                ('creador', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('plantilla_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prevencion.prevencionplantilla')),
            ],
        ),
        migrations.CreateModel(
            name='PrevencionEvidenciaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_seccion', models.IntegerField(help_text='Indice de la sección (0, 1, 2...)')),
                ('archivo', models.FileField(upload_to='prevencion/evidencias_secciones/')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_secciones', to='prevencion.prevenciondocumento')),
            ],
        ),
    ]
