# Generated by Django 4.2.11 on 2026-01-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0002_prevenciondocumento_prevencionevidenciaseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevenciondocumento',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='prevenciondocumento',
            name='contenido',
            field=models.JSONField(verbose_name='Contenido Relleno'),
        ),
        migrations.AlterField(
            model_name='prevenciondocumento',
            name='evidencia_general',
            field=models.FileField(blank=True, null=True, upload_to='prevencion/evidencias/'),
        ),
    ]
