# Generated by Django 4.2.11 on 2026-01-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0058_recomendacion_fechaupdateestado'),
        ('prevencion', '0003_prevenciondocumento_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilanciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_texto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Género')),
                ('fecha_examen', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_examen', models.CharField(choices=[('PRE_OCUPACIONAL', 'Pre-Ocupacional'), ('OCUPACIONAL', 'Ocupacional / Periódico'), ('VIGILANCIA', 'Vigilancia Específica'), ('EVALUACION', 'Evaluación de Egreso')], default='OCUPACIONAL', max_length=50)),
                ('organismo_administrador', models.CharField(default='ACHS', max_length=100, verbose_name='Organismo (Mutual/ACHS)')),
                ('clinica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clínica / Lugar')),
                ('estado_aptitud', models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Observaciones'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('observacion_medica', models.TextField(blank=True, null=True)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='prevencion/vigilancia_medica/')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('faena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faena', verbose_name='Faena')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vigilancias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
