# Generated by Django 4.2.11 on 2026-01-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0004_vigilanciamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='organismo_administrador',
            field=models.CharField(default='ACHS', max_length=100, verbose_name='Organismo'),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='rut_trabajador',
            field=models.CharField(max_length=20, verbose_name='RUT'),
        ),
    ]
