# Generated by Django 4.2.11 on 2026-01-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0005_alter_vigilanciamedica_organismo_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='observacion_medica',
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='bateria_examen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batería (Ej: Altura Física, Conductor)'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Recepción Informe'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='indicaciones_medicas',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Chilena', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='observacion_interna',
            field=models.TextField(blank=True, null=True, verbose_name='Obs. Interna Prevención'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='otros_riesgos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otros Riesgos'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='restricciones',
            field=models.TextField(blank=True, null=True, verbose_name='Restricciones'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_altura_fisica',
            field=models.BooleanField(default=False, verbose_name='Altura Física'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_altura_geo',
            field=models.BooleanField(default=False, verbose_name='Altura Geográfica'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_espacios_confinados',
            field=models.BooleanField(default=False, verbose_name='Espacios Confinados'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_mmc',
            field=models.BooleanField(default=False, verbose_name='Manejo Manual Cargas'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_polvo',
            field=models.BooleanField(default=False, verbose_name='Polvo'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_radiacion',
            field=models.BooleanField(default=False, verbose_name='Radiación UV'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_ruido',
            field=models.BooleanField(default=False, verbose_name='Ruido Ocupacional'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_silice',
            field=models.BooleanField(default=False, verbose_name='Sílice'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='riesgo_vibracion',
            field=models.BooleanField(default=False, verbose_name='Vibraciones'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='estado_aptitud',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Observaciones'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='tipo_examen',
            field=models.CharField(choices=[('PRE_OCUPACIONAL', 'Pre-Ocupacional'), ('OCUPACIONAL', 'Ocupacional / Periódico'), ('VIGILANCIA', 'Vigilancia Específica'), ('EVALUACION', 'Evaluación de Egreso'), ('PSICOSENSOTECNICO', 'Psicosensotécnico')], default='OCUPACIONAL', max_length=50),
        ),
    ]
