# Generated by Django 4.2.11 on 2026-01-21 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0006_remove_vigilanciamedica_observacion_medica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vigilanciamedica',
            old_name='fecha_vencimiento',
            new_name='ad_fecha',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='bateria_examen',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='estado_aptitud',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='fecha_examen',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='fecha_recepcion',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='indicaciones_medicas',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='observacion_interna',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='otros_riesgos',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='restricciones',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_altura_fisica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_altura_geo',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_espacios_confinados',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_mmc',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_polvo',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_radiacion',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_ruido',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_silice',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='riesgo_vibracion',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='tipo_examen',
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ad_aplica',
            field=models.BooleanField(default=False, verbose_name='Aplica Alcohol y Drogas'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ad_resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado A&D'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='af_aplica',
            field=models.BooleanField(default=False, verbose_name='Aplica Altura Física'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='af_estado',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Obs'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='af_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='af_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ag_aplica',
            field=models.BooleanField(default=False, verbose_name='Aplica Altura Geográfica'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ag_estado',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Obs'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ag_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ag_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ec_aplica',
            field=models.BooleanField(default=False, verbose_name='Aplica Espacios Confinados'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ec_estado',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Obs'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ec_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ec_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='eso_aplica',
            field=models.BooleanField(default=True, verbose_name='Aplica ESO'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='eso_estado',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Obs'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='eso_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='eso_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_operativo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha General Operativo'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='observacion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='psico_aplica',
            field=models.BooleanField(default=False, verbose_name='Aplica Psicosensotécnico'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='psico_estado',
            field=models.CharField(choices=[('APTO', 'Apto'), ('APTO_OBS', 'Apto con Obs'), ('NO_APTO', 'No Apto'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='psico_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='psico_vence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='genero_texto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
