# Generated by Django 4.2.11 on 2026-01-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_recomendacion_fechaupdateestado'),
        ('prevencion', '0007_rename_fecha_vencimiento_vigilanciamedica_ad_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vigilanciamedica',
            old_name='ad_fecha',
            new_name='hipo_fecha_vence',
        ),
        migrations.RenameField(
            model_name='vigilanciamedica',
            old_name='observacion_general',
            new_name='hipo_obs',
        ),
        migrations.RenameField(
            model_name='vigilanciamedica',
            old_name='af_fecha',
            new_name='ruido_fecha_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ad_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ad_resultado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='af_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='af_estado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='af_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ag_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ag_estado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ag_fecha',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ag_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ec_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ec_estado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ec_fecha',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='ec_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='eso_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='eso_estado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='eso_fecha',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='eso_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='fecha_operativo',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='organismo_administrador',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='psico_aplica',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='psico_estado',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='psico_fecha',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='psico_vence',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='antiguedad_anos',
            field=models.IntegerField(default=0, verbose_name='Años'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='antiguedad_dias',
            field=models.IntegerField(default=0, verbose_name='Días'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='antiguedad_meses',
            field=models.IntegerField(default=0, verbose_name='Meses'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Retiro o Desvinculación'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ges',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GES'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='hipo_exposicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exposición Hipobaria'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='hipo_fecha_hemo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Hemoglobina'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='hipo_vigencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='humos_eval_riesgo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='humos_exposicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='rad_exposicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_eval_riesgo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evaluación Riesgo Ruido'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_fecha_audio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Audiometría'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_grado_expo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_nivel_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='ruido_vigencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_eval_riesgo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Evaluación Riesgo Sílice'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_fecha_radio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Radiografía'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_fecha_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_grado_expo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado Exposición'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_nivel_riesgo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Sílice'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='silice_vigencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='vibra_eval_riesgo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='vibra_exposicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='faena',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faena'),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='genero_texto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
