# Generated by Django 4.2.11 on 2026-01-21 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0008_rename_ad_fecha_vigilanciamedica_hipo_fecha_vence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilanciamedica',
            name='clinica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clínica / Lugar'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_operativo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha General Operativo'),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='observacion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='organismo_administrador',
            field=models.CharField(default='ACHS', max_length=100, verbose_name='Organismo'),
        ),
    ]
