# Generated by Django 4.2.11 on 2026-01-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0009_vigilanciamedica_clinica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionEvidenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_seccion', models.IntegerField(help_text='Índice de la sección (0, 1, 2...)')),
                ('indice_fila', models.IntegerField(help_text='Índice de la fila/ítem (0, 1, 2...)')),
                ('archivo', models.FileField(upload_to='prevencion/evidencias_items/')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_items', to='prevencion.prevenciondocumento')),
            ],
            options={
                'unique_together': {('documento', 'indice_seccion', 'indice_fila')},
            },
        ),
    ]
