# Generated by Django 4.2.11 on 2026-01-21 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0010_prevencionevidenciaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilanciamedica',
            name='fecha_operativo',
        ),
        migrations.AddField(
            model_name='vigilanciamedica',
            name='fecha_incidente',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Incidente'),
        ),
    ]
