# Generated by Django 4.2.11 on 2026-01-22 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0011_remove_vigilanciamedica_fecha_operativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilanciamedica',
            name='fecha_incidente',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha Incidente'),
        ),
    ]
