# Generated by Django 4.2.11 on 2026-02-23 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0012_alter_vigilanciamedica_fecha_incidente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prevencionevidenciaitem',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PrevencionEvidenciaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='prevencion/evidencias_generales/')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_generales', to='prevencion.prevenciondocumento')),
            ],
        ),
    ]
