# Generated by Django 4.2.16 on 2026-02-26 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0013_alter_prevencionevidenciaitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilanciaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ges', 'GES'), ('area', 'Area'), ('cargo', 'Cargo'), ('tipo_contrato', 'Tipo de Contrato'), ('evaluacion_riesgo', 'Evaluacion de Riesgo'), ('exposicion', 'Exposicion'), ('nivel_riesgo', 'Nivel de Riesgo'), ('grado_exposicion', 'Grado de Exposicion'), ('nivel_seguimiento', 'Nivel de Seguimiento')], db_index=True, max_length=40, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Opcion Vigilancia',
                'verbose_name_plural': 'Opciones Vigilancia',
                'db_table': 'prevencion_vigilancia_opcion',
            },
        ),
        migrations.AddConstraint(
            model_name='vigilanciaopcion',
            constraint=models.UniqueConstraint(fields=('tipo', 'valor'), name='uq_prevencion_vigilancia_tipo_valor'),
        ),
    ]
