# Generated by Django 4.2.16 on 2026-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0015_vigilanciaopcion_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilanciamedica',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
