# Generated by Django 4.2.16 on 2026-02-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0016_vigilanciamedica_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilanciaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='prevencion/vigilancia_medica/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vigilancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_vigilancia', to='prevencion.vigilanciamedica')),
            ],
            options={
                'verbose_name': 'Adjunto Vigilancia',
                'verbose_name_plural': 'Adjuntos Vigilancia',
                'db_table': 'prevencion_vigilancia_adjunto',
                'ordering': ['id'],
            },
        ),
    ]
