# Generated by Django 4.2.11 on 2026-03-02 17:12

from django.db import migrations, models
import django.utils.timezone


def migrar_vigilancia_opciones(apps, schema_editor):
    VigilanciaOpcion = apps.get_model('prevencion', 'VigilanciaOpcion')
    modelos_destino = {
        'ges': apps.get_model('prevencion', 'VigilanciaGes'),
        'area': apps.get_model('prevencion', 'VigilanciaArea'),
        'cargo': apps.get_model('prevencion', 'VigilanciaCargo'),
        'tipo_contrato': apps.get_model('prevencion', 'VigilanciaTipoContrato'),
        'evaluacion_riesgo': apps.get_model('prevencion', 'VigilanciaEvaluacionRiesgo'),
        'exposicion': apps.get_model('prevencion', 'VigilanciaExposicion'),
        'nivel_riesgo': apps.get_model('prevencion', 'VigilanciaNivelRiesgo'),
        'grado_exposicion': apps.get_model('prevencion', 'VigilanciaGradoExposicion'),
        'nivel_seguimiento': apps.get_model('prevencion', 'VigilanciaNivelSeguimiento'),
    }

    for opcion in VigilanciaOpcion.objects.all().order_by('tipo', 'correlativo', 'id'):
        modelo_destino = modelos_destino.get(opcion.tipo)
        if not modelo_destino:
            continue

        modelo_destino.objects.create(
            correlativo=opcion.correlativo,
            valor=opcion.valor,
            status=opcion.status,
            creador=opcion.creador,
            fechacreacion=opcion.fechacreacion,
        )


def revertir_vigilancia_opciones(apps, schema_editor):
    VigilanciaOpcion = apps.get_model('prevencion', 'VigilanciaOpcion')
    modelos_origen = (
        ('ges', apps.get_model('prevencion', 'VigilanciaGes')),
        ('area', apps.get_model('prevencion', 'VigilanciaArea')),
        ('cargo', apps.get_model('prevencion', 'VigilanciaCargo')),
        ('tipo_contrato', apps.get_model('prevencion', 'VigilanciaTipoContrato')),
        ('evaluacion_riesgo', apps.get_model('prevencion', 'VigilanciaEvaluacionRiesgo')),
        ('exposicion', apps.get_model('prevencion', 'VigilanciaExposicion')),
        ('nivel_riesgo', apps.get_model('prevencion', 'VigilanciaNivelRiesgo')),
        ('grado_exposicion', apps.get_model('prevencion', 'VigilanciaGradoExposicion')),
        ('nivel_seguimiento', apps.get_model('prevencion', 'VigilanciaNivelSeguimiento')),
    )

    for tipo, modelo_origen in modelos_origen:
        for opcion in modelo_origen.objects.all().order_by('correlativo', 'id'):
            VigilanciaOpcion.objects.create(
                tipo=tipo,
                correlativo=opcion.correlativo,
                valor=opcion.valor,
                status=opcion.status,
                creador=opcion.creador,
                fechacreacion=opcion.fechacreacion,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0017_vigilanciaadjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilanciaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Area Vigilancia',
                'verbose_name_plural': 'Areas Vigilancia',
                'db_table': 'prevencion_vigilancia_area',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cargo Vigilancia',
                'verbose_name_plural': 'Cargos Vigilancia',
                'db_table': 'prevencion_vigilancia_cargo',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaEvaluacionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Evaluacion de Riesgo Vigilancia',
                'verbose_name_plural': 'Evaluaciones de Riesgo Vigilancia',
                'db_table': 'prevencion_vigilancia_evaluacion_riesgo',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Exposicion Vigilancia',
                'verbose_name_plural': 'Exposiciones Vigilancia',
                'db_table': 'prevencion_vigilancia_exposicion',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaGes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'GES Vigilancia',
                'verbose_name_plural': 'GES Vigilancia',
                'db_table': 'prevencion_vigilancia_ges',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaGradoExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Grado de Exposicion Vigilancia',
                'verbose_name_plural': 'Grados de Exposicion Vigilancia',
                'db_table': 'prevencion_vigilancia_grado_exposicion',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaNivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Nivel de Riesgo Vigilancia',
                'verbose_name_plural': 'Niveles de Riesgo Vigilancia',
                'db_table': 'prevencion_vigilancia_nivel_riesgo',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaNivelSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Nivel de Seguimiento Vigilancia',
                'verbose_name_plural': 'Niveles de Seguimiento Vigilancia',
                'db_table': 'prevencion_vigilancia_nivel_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='VigilanciaTipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tipo de Contrato Vigilancia',
                'verbose_name_plural': 'Tipos de Contrato Vigilancia',
                'db_table': 'prevencion_vigilancia_tipo_contrato',
            },
        ),
        migrations.RunPython(migrar_vigilancia_opciones, revertir_vigilancia_opciones),
        migrations.DeleteModel(
            name='VigilanciaOpcion',
        ),
        migrations.AddConstraint(
            model_name='vigilanciatipocontrato',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_tipo_contrato_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciatipocontrato',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_tipo_contrato_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilancianivelseguimiento',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_nivel_seguimiento_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilancianivelseguimiento',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_nivel_seguimiento_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilancianivelriesgo',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_nivel_riesgo_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilancianivelriesgo',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_nivel_riesgo_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciagradoexposicion',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_grado_exposicion_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciagradoexposicion',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_grado_exposicion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciages',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_ges_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciages',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_ges_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaexposicion',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_exposicion_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaexposicion',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_exposicion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaevaluacionriesgo',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_eval_riesgo_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaevaluacionriesgo',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_eval_riesgo_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciacargo',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_cargo_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciacargo',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_cargo_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaarea',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prevencion_vigilancia_area_valor'),
        ),
        migrations.AddConstraint(
            model_name='vigilanciaarea',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prevencion_vigilancia_area_correlativo'),
        ),
    ]
