# Generated by Django 4.2.11 on 2026-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0018_vigilanciaarea_vigilanciacargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevencionplantilla',
            name='tipo',
            field=models.CharField(choices=[('condiciones', 'Condiciones Generales'), ('silice', 'Silice'), ('ruido', 'Ruido'), ('hipobaria', 'Hipobaria'), ('psicosocial', 'Psicosocial'), ('tmert', 'TMERT'), ('mmc', 'MMC'), ('charlas', 'Charlas'), ('informativos', 'Informativos'), ('difusiones', 'Difusiones'), ('cursos', 'Cursos')], max_length=20, verbose_name='Tipo de Riesgo'),
        ),
    ]
