# Generated by Django 4.2.11 on 2026-03-11 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0019_alter_prevencionplantilla_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCharla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Charla',
                'verbose_name_plural': 'Charlas',
                'db_table': 'prevencion_documento_charla',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'prevencion_documento_curso',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDifusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Difusion',
                'verbose_name_plural': 'Difusiones',
                'db_table': 'prevencion_documento_difusion',
            },
        ),
        migrations.CreateModel(
            name='DocumentoInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.PositiveIntegerField(verbose_name='ID Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
                'db_table': 'prevencion_documento_informativo',
            },
        ),
        migrations.AddConstraint(
            model_name='documentoinformativo',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prev_doc_informativo_valor'),
        ),
        migrations.AddConstraint(
            model_name='documentoinformativo',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prev_doc_informativo_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='documentodifusion',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prev_doc_difusion_valor'),
        ),
        migrations.AddConstraint(
            model_name='documentodifusion',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prev_doc_difusion_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='documentocurso',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prev_doc_curso_valor'),
        ),
        migrations.AddConstraint(
            model_name='documentocurso',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prev_doc_curso_correlativo'),
        ),
        migrations.AddConstraint(
            model_name='documentocharla',
            constraint=models.UniqueConstraint(fields=('valor',), name='uq_prev_doc_charla_valor'),
        ),
        migrations.AddConstraint(
            model_name='documentocharla',
            constraint=models.UniqueConstraint(fields=('correlativo',), name='uq_prev_doc_charla_correlativo'),
        ),
    ]
