# Generated by Django 4.2.11 on 2026-03-11 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_programa_unique_together'),
        ('prevencion', '0020_documentocharla_documentocurso_documentodifusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionPermisoLlenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('creador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargos', models.ManyToManyField(blank=True, related_name='permisos_llenado', to='prevencion.vigilanciacargo')),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_prevencion_llenado', to='core.faena')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_llenado', to='prevencion.prevencionplantilla')),
            ],
            options={
                'verbose_name': 'Permiso de Llenado',
                'verbose_name_plural': 'Permisos de Llenado',
                'db_table': 'prevencion_permiso_llenado',
            },
        ),
        migrations.AddConstraint(
            model_name='prevencionpermisollenado',
            constraint=models.UniqueConstraint(fields=('faena', 'plantilla'), name='uq_prevencion_permiso_llenado_faena_plantilla'),
        ),
    ]
