# Generated by Django 4.2.11 on 2026-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0021_prevencionpermisollenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionplantilla',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prevencion/plantillas_pdf/', verbose_name='PDF de Plantilla'),
        ),
        migrations.AddField(
            model_name='prevencionplantilla',
            name='modo_contenido',
            field=models.CharField(choices=[('estructura', 'Crear Estructura'), ('pdf', 'Adjuntar PDF')], default='estructura', max_length=20, verbose_name='Modo de Contenido'),
        ),
    ]
