# Generated by Django 4.2.11 on 2026-03-24 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_programa_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prevencion', '0023_egreso_higienecualitativa_higienecuantitativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionDocumentoDifusionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=20, verbose_name='RUT')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Cargo')),
                ('area', models.CharField(blank=True, max_length=120, null=True, verbose_name='Area')),
                ('ges', models.CharField(blank=True, max_length=120, null=True, verbose_name='GES')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creador')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difusion_trabajadores', to='prevencion.prevenciondocumento')),
                ('faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_difusion_trabajadores', to='core.faena', verbose_name='Faena')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_difusion_trabajadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Difusion Documento Trabajador',
                'verbose_name_plural': 'Difusiones Documento Trabajadores',
                'db_table': 'prevencion_documento_difusion_trabajador',
            },
        ),
        migrations.AddConstraint(
            model_name='prevenciondocumentodifusiontrabajador',
            constraint=models.UniqueConstraint(fields=('documento', 'user'), name='uq_prev_doc_difusion_documento_user'),
        ),
    ]
