# Generated by Django 4.2.11 on 2026-03-25 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prevencion', '0024_prevenciondocumentodifusiontrabajador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionplantilla',
            name='autorizadores',
            field=models.ManyToManyField(blank=True, related_name='plantillas_prevencion_autorizadores', to=settings.AUTH_USER_MODEL, verbose_name='Autorizadores'),
        ),
    ]
