# Generated by Django 4.2.11 on 2026-03-25 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prevencion', '0025_prevencionplantilla_autorizadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionNotificacionAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=20, verbose_name='Tipo Documento')),
                ('titulo', models.CharField(default='Solicitud de aprobación de títulos', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lectura')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Respuesta')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_prevencion_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_aprobacion', to='prevencion.prevencionplantilla', verbose_name='Plantilla')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_prevencion_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Notificación Aprobación Prevención',
                'verbose_name_plural': 'Notificaciones Aprobación Prevención',
                'db_table': 'prevencion_notificacion_aprobacion',
                'ordering': ['-fechacreacion'],
                'indexes': [models.Index(fields=['destinatario', 'estado'], name='prevencion__destina_7bcd2c_idx'), models.Index(fields=['solicitante', 'estado'], name='prevencion__solicit_93fea8_idx')],
            },
        ),
    ]
