# Generated by Django 4.2.11 on 2026-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0026_prevencionnotificacionaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionplantilla',
            name='autorizacion_incompleta',
            field=models.BooleanField(default=False, verbose_name='Autorización Incompleta'),
        ),
    ]

