# Generated by Django 4.2.11 on 2026-03-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prevencion', '0027_prevencionplantilla_autorizacion_incompleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionHistorialAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('agregado', 'Agregado'), ('eliminado', 'Eliminado')], max_length=20, verbose_name='Acción')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_autorizacion_realizado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el cambio')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_autorizacion_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador afectado')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_autorizacion', to='prevencion.prevencionplantilla', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Historial de Autorización Prevención',
                'verbose_name_plural': 'Historiales de Autorización Prevención',
                'db_table': 'prevencion_historial_autorizacion',
                'ordering': ['-fechacreacion', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='prevencionhistorialautorizacion',
            index=models.Index(fields=['plantilla', 'fechacreacion'], name='prevencion__plantil_45b8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='prevencionhistorialautorizacion',
            index=models.Index(fields=['accion'], name='prevencion__accion_e0e5bc_idx'),
        ),
    ]
