# Generated by Django 4.2.11 on 2026-03-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0028_prevencionhistorialautorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionnotificacionaprobacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo Rechazo'),
        ),
    ]
