# Generated by Django 4.2.11 on 2026-03-26 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0029_prevencionnotificacionaprobacion_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionNotificacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=20, verbose_name='Tipo Documento')),
                ('titulo', models.CharField(default='Documento disponible', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('vista', 'Vista')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Lectura')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_documento_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_documento', to='prevencion.prevenciondocumento', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Notificación Documento Prevención',
                'verbose_name_plural': 'Notificaciones Documento Prevención',
                'db_table': 'prevencion_notificacion_documento',
                'ordering': ['-fechacreacion', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='prevencionnotificaciondocumento',
            constraint=models.UniqueConstraint(fields=('destinatario', 'documento'), name='uq_prev_notif_documento_destinatario_documento'),
        ),
        migrations.AddIndex(
            model_name='prevencionnotificaciondocumento',
            index=models.Index(fields=['destinatario', 'estado'], name='prevencion_n_destina_4869df_idx'),
        ),
        migrations.AddIndex(
            model_name='prevencionnotificaciondocumento',
            index=models.Index(fields=['documento', 'estado'], name='prevencion_n_documen_56dd2e_idx'),
        ),
    ]
