# Generated by Django 4.2.11 on 2026-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0030_prevencionnotificaciondocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionplantilla',
            name='tiempo_estimado_minutos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (minutos)'),
        ),
    ]

