# Generated by Django 4.2.11 on 2026-03-29 20:58

from django.db import migrations, models
import django.db.models.deletion


def backfill_documento_adjunto_cargado_at(apps, schema_editor):
    Egreso = apps.get_model('prevencion', 'Egreso')
    registros = (
        Egreso.objects.filter(
            documento_adjunto__isnull=False,
            documento_adjunto_cargado_at__isnull=True,
        )
        .exclude(documento_adjunto='')
    )

    for egreso in registros.iterator():
        fecha_carga = egreso.fecha_egreso or egreso.created_at
        if fecha_carga:
            Egreso.objects.filter(pk=egreso.pk).update(documento_adjunto_cargado_at=fecha_carga)


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0031_prevencionplantilla_tiempo_estimado_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoAdjuntoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='prevencion/egreso/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto Historico Egreso',
                'verbose_name_plural': 'Adjuntos Historicos Egreso',
                'db_table': 'prevencion_egreso_adjunto_historico',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='documento_adjunto_cargado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='egresoadjuntohistorico',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_historicos', to='prevencion.egreso'),
        ),
        migrations.RunPython(backfill_documento_adjunto_cargado_at, migrations.RunPython.noop),
    ]
