# Generated by Django 4.2.11 on 2026-03-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0031_prevencionplantilla_tiempo_estimado_minutos'),
    ]

    operations = []
