# Generated by Django 4.2.11 on 2026-03-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0032_egresoadjuntohistorico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionResultadoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_preguntas', models.PositiveIntegerField(default=0, verbose_name='Total Preguntas')),
                ('total_correctas', models.PositiveIntegerField(default=0, verbose_name='Total Correctas')),
                ('porcentaje_aprobacion', models.FloatField(default=0, verbose_name='Porcentaje Aprobación')),
                ('detalle_respuestas', models.JSONField(blank=True, default=list, verbose_name='Detalle Respuestas')),
                ('fechacreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_curso', to='prevencion.prevenciondocumento', verbose_name='Documento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_curso_prevencion', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Resultado Curso',
                'verbose_name_plural': 'Resultados Curso',
                'db_table': 'prevencion_resultado_curso',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='prevencionresultadocurso',
            constraint=models.UniqueConstraint(fields=('documento', 'trabajador'), name='uq_prev_resultado_curso_documento_trabajador'),
        ),
        migrations.AddIndex(
            model_name='prevencionresultadocurso',
            index=models.Index(fields=['documento', 'trabajador'], name='prevencion__documen_bb5251_idx'),
        ),
        migrations.AddIndex(
            model_name='prevencionresultadocurso',
            index=models.Index(fields=['trabajador', 'updated_at'], name='prevencion__trabaja_6f79d6_idx'),
        ),
    ]
