# Generated by Django 4.2.11 on 2026-03-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0032_rename_prevencion__plantil_45b8d7_idx_prevencion__plantil_6f2c6f_idx_and_more'),
        ('prevencion', '0033_prevencionresultadocurso'),
    ]

    operations = [
    ]
