# Generated by Django 4.2.11 on 2026-04-01 13:05

from django.db import migrations, models


def set_course_defaults(apps, schema_editor):
    PrevencionPlantilla = apps.get_model('prevencion', 'PrevencionPlantilla')
    PrevencionPlantilla.objects.filter(tipo='cursos').update(
        curso_total_intentos=2,
        curso_porcentaje_aprobacion=60,
    )


def unset_course_defaults(apps, schema_editor):
    PrevencionPlantilla = apps.get_model('prevencion', 'PrevencionPlantilla')
    PrevencionPlantilla.objects.filter(tipo='cursos').update(
        curso_total_intentos=None,
        curso_porcentaje_aprobacion=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0034_merge_20260331_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionplantilla',
            name='curso_porcentaje_aprobacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Curso: Porcentaje aprobación'),
        ),
        migrations.AddField(
            model_name='prevencionplantilla',
            name='curso_total_intentos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Curso: Total intentos'),
        ),
        migrations.RunPython(set_course_defaults, unset_course_defaults),
    ]
