# Generated by Django 4.2.11 on 2026-04-01 18:10

from django.db import migrations, models


CURSO_PORCENTAJE_APROBACION_DEFAULT = 60


def backfill_course_result_state(apps, schema_editor):
    PrevencionResultadoCurso = apps.get_model('prevencion', 'PrevencionResultadoCurso')

    resultados_qs = PrevencionResultadoCurso.objects.select_related(
        'documento',
        'documento__plantilla_base',
    )

    for resultado in resultados_qs.iterator():
        intentos_realizados = int(getattr(resultado, 'intentos_realizados', 0) or 0)
        porcentaje_obtenido = float(getattr(resultado, 'porcentaje_aprobacion', 0.0) or 0.0)

        tuvo_resultado = bool(
            int(getattr(resultado, 'total_preguntas', 0) or 0) > 0
            or int(getattr(resultado, 'total_correctas', 0) or 0) > 0
            or porcentaje_obtenido > 0
            or bool(getattr(resultado, 'detalle_respuestas', None))
        )
        if intentos_realizados <= 0 and tuvo_resultado:
            intentos_realizados = 1

        plantilla = getattr(getattr(resultado, 'documento', None), 'plantilla_base', None)
        porcentaje_requerido = int(
            getattr(plantilla, 'curso_porcentaje_aprobacion', 0)
            or CURSO_PORCENTAJE_APROBACION_DEFAULT
        )
        aprobado = bool(intentos_realizados > 0 and porcentaje_obtenido >= float(porcentaje_requerido))

        resultado.intentos_realizados = intentos_realizados
        resultado.aprobado = aprobado
        resultado.save(update_fields=['intentos_realizados', 'aprobado'])


def clear_course_result_state(apps, schema_editor):
    PrevencionResultadoCurso = apps.get_model('prevencion', 'PrevencionResultadoCurso')
    PrevencionResultadoCurso.objects.all().update(
        intentos_realizados=0,
        aprobado=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0035_prevencionplantilla_curso_intentos_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionresultadocurso',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='prevencionresultadocurso',
            name='intentos_realizados',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos Realizados'),
        ),
        migrations.RunPython(backfill_course_result_state, clear_course_result_state),
    ]
