# Generated by Django 4.2.11 on 2026-04-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0039_prevencionhistorialdifusiontrabajador'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prevencionhistorialautorizacion',
            new_name='prevencion__plantil_6f2c6f_idx',
            old_name='prevencion__plantil_45b8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionhistorialautorizacion',
            new_name='prevencion__accion_a1bd30_idx',
            old_name='prevencion__accion_e0e5bc_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionhistorialdifusiontrabajador',
            new_name='prevencion__documen_d46636_idx',
            old_name='prevencion__documen_2ea83b_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionhistorialdifusiontrabajador',
            new_name='prevencion__accion_a1f2d7_idx',
            old_name='prevencion__accion_94d0f8_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionhistorialdifusiontrabajador',
            new_name='prevencion__trabaja_3e35bf_idx',
            old_name='prevencion__trabaja_ea531e_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionnotificaciondocumento',
            new_name='prevencion__destina_066ad9_idx',
            old_name='prevencion_n_destina_4869df_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionnotificaciondocumento',
            new_name='prevencion__documen_89b1d7_idx',
            old_name='prevencion_n_documen_56dd2e_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionresultadocurso',
            new_name='prevencion__documen_7b714f_idx',
            old_name='prevencion__documen_bb5251_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionresultadocurso',
            new_name='prevencion__trabaja_a5b985_idx',
            old_name='prevencion__trabaja_6f79d6_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionresultadocursointento',
            new_name='prevencion__documen_c5d14f_idx',
            old_name='prevencion__documen_7fbad0_idx',
        ),
        migrations.RenameIndex(
            model_name='prevencionresultadocursointento',
            new_name='prevencion__trabaja_68c9da_idx',
            old_name='prevencion__trabaja_937969_idx',
        ),
    ]
