# Generated by Django 4.2.11 on 2026-05-18 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prevencion', '0040_rename_prevencion__plantil_45b8d7_idx_prevencion__plantil_6f2c6f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionDobleFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('documento_id', models.IntegerField()),
                ('rut_esperado', models.CharField(max_length=12)),
                ('validado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
