# Generated by Django 4.2.11 on 2026-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0041_validaciondoblefactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevenciondocumentodifusiontrabajador',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
