# Generated by Django 4.2.11 on 2026-05-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0042_prevenciondocumentodifusiontrabajador_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='validaciondoblefactor',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
