# Generated by Django 4.2.11 on 2026-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0043_validaciondoblefactor_en_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevencionresultadocursointento',
            name='tiempo_segundos',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo empleado (segundos)'),
        ),
    ]
