# Generated by Django 4.2.11 on 2026-04-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_programa_unique_together'),
        ('checklist', '0012_alter_estadoetapasreportedigital_checklistentrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='agregar',
            field=models.IntegerField(default=0, verbose_name='Agregar'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='checklistmaterialessonda',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='HistorialMovimientoCaseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('MODIFICACION', 'Modificación')], max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('sondaje', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_sondaje', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='historial_caseta/')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materialescaseta')),
            ],
        ),
    ]
