# Generated by Django 4.2.11 on 2026-04-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_checklistmaterialessonda_agregar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientocaseta',
            name='cantidad_buenos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialmovimientocaseta',
            name='cantidad_malos',
            field=models.IntegerField(default=0),
        ),
    ]
