# Generated by Django 4.2.11 on 2026-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_historialmovimientocaseta_cantidad_buenos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialescaseta',
            name='nombre_caseta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
