# Generated by Django 4.2.11 on 2026-05-07 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0016_checklistmaterialescaseta_nombre_caseta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasetaSondajeAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_checklist', models.CharField(max_length=100)),
                ('nombre_caseta', models.CharField(blank=True, max_length=100, null=True)),
                ('sondaje', models.CharField(max_length=100)),
                ('numero_sondaje', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checklist_caseta_sondaje_asociado',
            },
        ),
        migrations.AddField(
            model_name='checklistmaterialescaseta',
            name='numero_sondaje_asociado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklistmaterialescaseta',
            name='sondaje_asociado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialmovimientocaseta',
            name='id_checklist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
