# Generated by Django 4.2.11 on 2026-05-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0017_casetasondajeasociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistmaterialescaseta',
            name='usar_en_reporte',
            field=models.BooleanField(default=True, verbose_name='Utilizar material en reporte'),
        ),
    ]
