# Generated by Django 4.2.11 on 2026-05-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0019_alter_checklistmaterialescaseta_usar_en_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmaterialescaseta',
            name='usar_en_reporte',
            field=models.BooleanField(default=True, verbose_name='Utilizar material en reporte'),
        ),
    ]
