# Generated by Django 4.2.11 on 2026-04-27 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT')),
                ('nombre_usuario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo')),
                ('rol_usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Modificación')),
                ('seccion', models.CharField(max_length=100, verbose_name='Sección del Sistema')),
                ('modelo_afectado', models.CharField(max_length=100, verbose_name='Modelo/Formulario')),
                ('registro_id', models.IntegerField(verbose_name='ID del Registro')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historiales de Cambios',
                'db_table': 'admin_audit_log',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
