# Generated by Django 4.2.11 on 2026-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Acción Realizada'),
        ),
    ]
