# Generated by Django 4.2.11 on 2026-04-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_historialcambio_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambio',
            name='accion',
        ),
    ]
