# Generated by Django 4.2.11 on 2026-04-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_historialcambio_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(choices=[('Creación', 'Creación'), ('Edición', 'Edición'), ('Eliminación', 'Eliminación')], default='Edición', max_length=20, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='representacion_registro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro Afectado'),
        ),
    ]
