# Generated by Django 4.2.11 on 2026-04-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_historialcambio_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambio',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='historialcambio',
            name='representacion_registro',
        ),
    ]
