# Generated by Django 4.2.11 on 2026-04-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_historialcambio_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='identificador_registro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Identificador'),
        ),
    ]
