# Generated by Django 4.2.11 on 2026-04-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_historialcambio_identificador_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambio',
            name='identificador_registro',
        ),
    ]
