# Generated by Django 4.2.11 on 2026-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_historialcambio_identificador_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='accion',
            field=models.CharField(default='Editado', max_length=20, verbose_name='Acción'),
        ),
    ]
