# Generated by Django 4.2.11 on 2026-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_historialcambio_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='nombre_registro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro Afectado'),
        ),
    ]
